**Evaluación de la germinación de semillas de Arveja con y sin luz**

El presente estudio evalúa el efecto de la luz sobre la germinación y el crecimiento inicial de semillas de arveja (Pisum sativum), una especie de gran importancia agrícola y alimentaria. La germinación es un proceso fisiológico fundamental que marca el inicio del desarrollo de la planta y está influenciado por diversos factores ambientales, entre los cuales la luz puede desempeñar un papel regulador dependiendo de la especie.

En este experimento se compararon dos condiciones: presencia de luz y ausencia de luz (oscuridad), con el fin de determinar si este factor afecta el porcentaje de germinación y el desarrollo inicial de las plántulas. Para ello, se registró el número de semillas germinadas a lo largo del tiempo y se evaluaron características de crecimiento como la longitud de las plántulas.

Author: 

JHAN FRANCO CASTRO CAJO 
ROYBER CHUQUIZUTA GUELAC
RUBEN SANCHEZ ALVARADO 
EMERSON SANTOS PELAEZ 
JHONEYDA EMELIS VERA CAMPOS 


## Database

> https://docs.google.com/spreadsheets/d/10O-qCTMryolQLBQICV9gyMJZdMv2-3DpYpFJQx4yLHQ/edit?gid=2079223155#gid=2079223155

## Reporte _ pagina web

> https://sanchez25-r.github.io/SEMILLAS_UI_GRUPO2/


⇒ *Documentos REPORTE 1*

> https://docs.google.com/document/d/1W6i3mLsVGW27EKXz3hrJEB4LWRL_n30rfakHUOhVF1c/edit?tab=t.0

